name = "DataCollocations"
uuid = "9454e98c-75cb-4dbc-9573-481819719962"
version = "1.1.0"
authors = ["SciML Contributors"]

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"

[extensions]
DataCollocationsDataInterpolationsExt = "DataInterpolations"

[compat]
ArrayInterface = "7"
DataInterpolations = "6.4, 7, 8"
JLArrays = "0.3"
julia = "1.10"

[extras]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["Documenter", "DataInterpolations", "OrdinaryDiffEq", "Plots"]
test = ["DataInterpolations", "JET", "JLArrays", "OrdinaryDiffEq", "Test"]
